import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — Apollo",
  description: "Apollo terms of service and conditions of use.",
};

export default function TermsOfServicePage() {
  return (
    <div className="space-y-10">
      {/* Page header */}
      <div>
        <h1 className="font-brand text-3xl font-medium tracking-tight text-[#2F2F2F]">
          Terms of Service
        </h1>
        <p className="mt-2 text-sm text-[#9CA3AF]">Last updated: 18 February 2026</p>
      </div>

      {/* Content card */}
      <div className="rounded-xl border border-black/[0.06] bg-white/80 p-6 shadow-[0_2px_20px_rgba(0,0,0,0.04)] md:p-8">
        <div className="space-y-8">

          <section>
            <h2 className="font-heading text-lg font-semibold text-[#2F2F2F]">1. Service Description</h2>
            <p className="mt-3 text-sm leading-relaxed text-[#4A4A4A]">
              <span className="font-brand">Apollo</span> is an AI-powered thesis generation platform
              operated by SciScribe Solutions (OPC) Pvt Ltd (&ldquo;SciScribe&rdquo;, &ldquo;we&rdquo;,
              &ldquo;us&rdquo;). The platform assists Indian medical postgraduate students in creating
              structured, university-compliant theses through AI-assisted content generation, statistical
              analysis, and LaTeX compilation.
            </p>
          </section>

          <hr className="border-black/[0.06]" />

          <section>
            <h2 className="font-heading text-lg font-semibold text-[#2F2F2F]">2. Account Registration</h2>
            <p className="mt-3 text-sm leading-relaxed text-[#4A4A4A]">
              To use <span className="font-brand">Apollo</span>, you must create an account with a valid
              email address. You are responsible for maintaining the confidentiality of your account
              credentials and for all activities that occur under your account. You must be at least 18
              years of age to use this service.
            </p>
          </section>

          <hr className="border-black/[0.06]" />

          <section>
            <h2 className="font-heading text-lg font-semibold text-[#2F2F2F]">3. Academic Integrity</h2>
            <div className="mt-3 space-y-2 text-sm leading-relaxed text-[#4A4A4A]">
              <p>
                <span className="font-brand">Apollo</span> is a writing assistance tool. All content
                generated by the platform is intended as a starting point and must be reviewed, verified,
                and modified by you before submission. You bear full responsibility for the academic
                integrity of your thesis. It is your obligation to:
              </p>
              <ul className="ml-4 list-disc space-y-1.5 marker:text-[#9CA3AF]">
                <li>Review and verify all AI-generated content for accuracy</li>
                <li>Ensure all citations and references are correct and verifiable</li>
                <li>Comply with your university&apos;s guidelines on AI-assisted writing tools</li>
                <li>Declare the use of AI assistance as required by your institution</li>
              </ul>
            </div>
          </section>

          <hr className="border-black/[0.06]" />

          <section>
            <h2 className="font-heading text-lg font-semibold text-[#2F2F2F]">4. Thesis Licences</h2>
            <p className="mt-3 text-sm leading-relaxed text-[#4A4A4A]">
              Access to <span className="font-brand">Apollo</span>&apos;s full features requires a thesis
              licence. Each licence is bound to one thesis project and is non-transferable (except as
              permitted by the platform&apos;s transfer mechanism). Thesis licences are non-refundable
              digital goods. See our{" "}
              <Link href="/refund" className="text-[#2F2F2F] underline underline-offset-2 decoration-[#9CA3AF] hover:decoration-[#2F2F2F]">
                Refund Policy
              </Link>{" "}
              for details.
            </p>
          </section>

          <hr className="border-black/[0.06]" />

          <section>
            <h2 className="font-heading text-lg font-semibold text-[#2F2F2F]">5. Acceptable Use</h2>
            <div className="mt-3 space-y-2 text-sm leading-relaxed text-[#4A4A4A]">
              <p>You agree not to:</p>
              <ul className="ml-4 list-disc space-y-1.5 marker:text-[#9CA3AF]">
                <li>Upload plagiarised content or content that is not your own work</li>
                <li>
                  Upload patient-identifiable data (names, medical record numbers, Aadhaar numbers,
                  dates of birth, or any other personally identifiable information)
                </li>
                <li>Use the platform to generate content for others without their knowledge</li>
                <li>Attempt to circumvent usage limits, authentication, or security measures</li>
                <li>Reverse-engineer or redistribute generated content as a commercial service</li>
              </ul>
            </div>
          </section>

          <hr className="border-black/[0.06]" />

          <section>
            <h2 className="font-heading text-lg font-semibold text-[#2F2F2F]">6. Intellectual Property</h2>
            <p className="mt-3 text-sm leading-relaxed text-[#4A4A4A]">
              You retain full ownership of all thesis content you create using{" "}
              <span className="font-brand">Apollo</span>. SciScribe claims no intellectual property rights
              over your thesis, synopsis, datasets, or AI-generated content. We retain the right to use
              anonymised, aggregated usage data for service improvement purposes only.
            </p>
          </section>

          <hr className="border-black/[0.06]" />

          <section>
            <h2 className="font-heading text-lg font-semibold text-[#2F2F2F]">7. Limitation of Liability</h2>
            <div className="mt-3 space-y-2 text-sm leading-relaxed text-[#4A4A4A]">
              <p>
                <span className="font-brand">Apollo</span> is provided &ldquo;as is&rdquo; without
                warranties of any kind, express or implied. SciScribe is not responsible for:
              </p>
              <ul className="ml-4 list-disc space-y-1.5 marker:text-[#9CA3AF]">
                <li>Academic outcomes, grades, or thesis acceptance decisions</li>
                <li>Accuracy of AI-generated content, statistical analyses, or citations</li>
                <li>Data loss due to circumstances beyond our reasonable control</li>
                <li>University-specific formatting requirements not covered by supported templates</li>
              </ul>
              <p>
                In no event shall SciScribe&apos;s total liability exceed the amount you paid for the
                thesis licence giving rise to the claim.
              </p>
            </div>
          </section>

          <hr className="border-black/[0.06]" />

          <section>
            <h2 className="font-heading text-lg font-semibold text-[#2F2F2F]">8. Account Termination</h2>
            <div className="mt-3 space-y-2 text-sm leading-relaxed text-[#4A4A4A]">
              <p>
                We reserve the right to suspend or terminate your account if you violate these Terms of
                Service, including but not limited to uploading patient-identifiable data, engaging in
                academic dishonesty, or abusing the platform. Your rights under the DPDP Act, 2023,
                including the right to data erasure, are preserved regardless of the reason for
                termination.
              </p>
              <p>
                You may delete your account at any time through the Settings page. Account deletion is
                subject to a 7-day cooling-off period, after which all data is permanently purged.
              </p>
            </div>
          </section>

          <hr className="border-black/[0.06]" />

          <section>
            <h2 className="font-heading text-lg font-semibold text-[#2F2F2F]">9. Governing Law</h2>
            <p className="mt-3 text-sm leading-relaxed text-[#4A4A4A]">
              These Terms of Service are governed by and construed in accordance with the laws of India.
              Any disputes arising from these terms shall be subject to the exclusive jurisdiction of the
              courts of Assam, India.
            </p>
          </section>

          <hr className="border-black/[0.06]" />

          <section>
            <h2 className="font-heading text-lg font-semibold text-[#2F2F2F]">10. Contact</h2>
            <p className="mt-3 text-sm leading-relaxed text-[#4A4A4A]">
              For any queries regarding these terms, contact us at:{" "}
              <a href="mailto:support@sciscribesolutions.com" className="text-[#2F2F2F] underline underline-offset-2 decoration-[#9CA3AF] hover:decoration-[#2F2F2F]">
                support@sciscribesolutions.com
              </a>
            </p>
          </section>

        </div>
      </div>
    </div>
  );
}
